import Head from "next/head";

import { Inter } from "next/font/google";
import AppNav from "@/components/AppNav";
import Footer from "@/components/Footer";
import styled from "styled-components";
import BlogSection from "@/components/BlogSection";
import CardsContainer from "@/components/CardsContainer";
import { useEffect, useState } from "react";
import VisitCard from "@/components/VisitCard";
import { blogs } from "@/app/constants";

const inter = Inter({ subsets: ["latin"] });

const HomeContainer = styled.div`
  min-height: calc(100vh - 75px - 55px);
  display: flex;
  justify-content: center;
  flex-direction: column;
`;

export default function Home() {
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);

  if (!domLoaded) return;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&family=Poppins:wght@200;300;400;600;700;800&family=Roboto:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <AppNav />
        <HomeContainer>
          <BlogSection title="Beyond the screen" />
          <CardsContainer blogs={blogs.slice(0, 3)} />
          <VisitCard />
        </HomeContainer>
        <Footer />
      </div>
    </>
  );
}
